Vagrant.configure("2") do |config|
  config.vm.define "centos7-practice" do |agent|
	agent.vm.box = "centos/7"
	agent.vm.hostname = "centor7-practice"
	agent.vm.network "private_network", ip: "172.42.42.205"
	agent.vm.provider "virtualbox" do |v|
	  v.memory = 1000
	  v.cpus = 2
	end
	agent.vm.provision "shell", inline: <<-SHELL
	sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
	sudo systemctl reload sshd
	### Install Docker
	sudo yum install -y yum-utils device-mapper-persistent-data lvm2
	sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	sudo yum install docker-ce docker-ce-cli containerd.io -y
	sudo systemctl enable docker 
	sudo systemctl start docker
	SHELL
  end
end
